name: virtual_try_on
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  get: ^5.0.0-release-candidate-5
  supabase_flutter: ^1.10.24
  smooth_page_indicator: ^1.1.0
  flutter_remix: ^0.0.3
  intl_phone_number_input: ^0.7.3+1
  dropdown_textfield: ^1.0.8
  pinput: ^3.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  expandable_text: ^2.3.0
  model_viewer_plus: ^1.5.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  dotted_line: ^3.2.2
  custom_navigation_bar: ^0.8.2
  flutter_easyloading: ^3.0.5
  image_picker: ^1.0.4
  buttons_tabbar: ^1.3.8
  expansion_tile_card: ^3.0.0


dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/loogo.png"
  min_sdk_android: 21 
  adaptive_icon_background: #ffffff
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
